### ISSUE TITLE
truncate.right(str, chars) doesn't work properly

### ISSUE THREAD

**Issue by stephenmathieson** [component/truncate#2]
`truncate.right(killbill, 20) == 'her lover "Bill".')` but `'her lover "Bill".'.length == 17`

**Comment by stephenmathieson** [comment]
@retrofox here's what i'm using atm:

``` js
exports.right = function (str, len, prefix) {
  str = str || '';
  len = len || 200;
  prefix = prefix || '';

  var length = str.length;

  return (len < length) ? prefix + str.substring(length - len, length) : str;
};
```

if you like, i can open a pr

**Comment by retrofox** [comment]
@stephenmathieson are you keep in mind the words? The idea is not cut words.

**Comment by stephenmathieson** [comment]
nope, didn't consider that at all

**Comment by retrofox** [comment]
This is the goal of this component. ;-)

**Comment by jonathanong** [comment]
sounds like this issue can be closed :P

**Comment by stephenmathieson** [comment]
@jonathanong does the test added in #3 pass now?

**Comment by jonathanong** [comment]
haha shoot didn't realize there was a failing test. fixed it and pushing now

**Comment by stephenmathieson** [comment]
nice, thanks!
